ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CHARGED_BACK';

ALTER TYPE "PaymentAttemptStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "PaymentAttemptStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED';
ALTER TYPE "PaymentAttemptStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE "PaymentAttemptStatus" ADD VALUE IF NOT EXISTS 'CHARGED_BACK';

CREATE TYPE "OrderPaymentKind" AS ENUM ('PAYMENT', 'REFUND', 'CHARGEBACK');
CREATE TYPE "PaymentWebhookEventStatus" AS ENUM (
    'RECEIVED',
    'PROCESSING',
    'PROCESSED',
    'FAILED',
    'IGNORED'
);
